src/AspNetCoreBlogList/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCoreBlogList.Models
{
    public class BlogPost
    {
        [Key]
        [ScaffoldColumn(false)]
        public int BlogPostId { get; set; }

        [Display(Name = "Blog Post Title")]
        [Required]
        public string BlogPostTitle { get; set; }

        [Display(Name = "Featured Image")]
        public byte[] BlogPostImage { get; set; }

        [Display(Name = "Author")]
        public string BlogAuthor { get; set; }

        [RegularExpression(@"^@?(\w){1,15}$", ErrorMessage = "Enter a valid user name")]
        [Display(Name = "Twitter Handle")]
        public string TwitterHandle { get; set; }

        [Display(Name = "Blog Post Link")]
        [Required]
        public string BlogPostLink { get; set; }

        [Display(Name = "Version")]
        [Required]
        public AspNetCoreVersion AspNetCoreVersion { get; set;}
    }

    public enum AspNetCoreVersion
    {
        ASPNETCoreRTM,
        ASPNETCoreRC2,
        ASPNETCoreRC1,
        AllVersions
    }
}

src/AspNetCoreBlogList/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreBlogList.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace AspNetCoreBlogList.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly BlogPostContext _context;

        public async Task<ActionResult> RenderImage(int id)
        {
            BlogPost blog = await _context.BlogPosts.SingleOrDefaultAsync(m => m.BlogPostId == id);
            byte[] itemImage = blog.BlogPostImage;
            return File(itemImage, "image/png");
        }

        public BlogPostsController(BlogPostContext context)
        {
            _context = context;    
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            return View(await _context.BlogPosts.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.BlogPosts.SingleOrDefaultAsync(m => m.BlogPostId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogPostId,AspNetCoreVersion,BlogPostLink,BlogPostTitle,BlogAuthor,TwitterHandle")] BlogPost blog, IFormFile blogImage)
        {
            if (ModelState.IsValid)
            {
                if (blogImage != null)
                {
                    blog.BlogPostImage = await GetBytes(blogImage);
                }

                if (!string.IsNullOrEmpty(blog.BlogPostLink))
                {
                    blog.BlogPostLink = GetUri(blog.BlogPostLink);
                }

                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(blog);
        }


        public async Task<byte[]> GetBytes(IFormFile file)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                await file.CopyToAsync(ms);
                return ms.ToArray();
            }
        }

        public string GetUri(string s)
        {
            return new UriBuilder(s).Uri.ToString();
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.BlogPosts.SingleOrDefaultAsync(m => m.BlogPostId == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogPostId,AspNetCoreVersion,BlogPostLink,BlogPostTitle,BlogAuthor,TwitterHandle")] BlogPost blog, IFormFile blogImage)
        {
            if (id != blog.BlogPostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (blogImage != null)
                    {
                        blog.BlogPostImage = await GetBytes(blogImage);
                    }

                    if (!string.IsNullOrEmpty(blog.BlogPostLink))
                    {
                        blog.BlogPostLink = GetUri(blog.BlogPostLink);
                    }

                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogPostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.BlogPosts.SingleOrDefaultAsync(m => m.BlogPostId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.BlogPosts.SingleOrDefaultAsync(m => m.BlogPostId == id);
            _context.BlogPosts.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BlogExists(int id)
        {
            return _context.BlogPosts.Any(e => e.BlogPostId == id);
        }
    }
}

src/AspNetCoreBlogList/Views/BlogPosts/Create.cshtml
@model AspNetCoreBlogList.Models.BlogPost

@{
    ViewData["Title"] = "Create Blog Post Entry";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>ASP.NET Blog Post Entry</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="BlogPostImage" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostImage" type="file" name="blogImage" class="form-control" />
                <span asp-validation-for="BlogPostImage" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogPostTitle" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostTitle" class="form-control" />
                <span asp-validation-for="BlogPostTitle" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogAuthor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogAuthor" class="form-control" />
                <span asp-validation-for="BlogAuthor" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TwitterHandle" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TwitterHandle" class="form-control" />
                <span asp-validation-for="TwitterHandle" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogPostLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostLink" class="form-control" />
                <span asp-validation-for="BlogPostLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AspNetCoreVersion" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="AspNetCoreVersion" asp-items="Html.GetEnumSelectList<AspNetCoreVersion>()" class="form-control"></select>
                <span asp-validation-for="AspNetCoreVersion" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/AspNetCoreBlogList/Views/BlogPosts/Delete.cshtml
@model AspNetCoreBlogList.Models.BlogPost

@{
    ViewData["Title"] = "Delete ASP.NET Blog Post Entry";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ASP.NET Blog Post Entry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostImage)
        </dt>
        <dd>
            <img src="@Url.Action("RenderImage", new { Id= Model.BlogPostId })" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BlogPostTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogAuthor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BlogAuthor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TwitterHandle)
        </dt>
        <dd>
            <a asp-protocol="https" asp-host="twitter.com" asp-controller="@Model.TwitterHandle">@Html.DisplayFor(modelItem => Model.TwitterHandle)</a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostLink)
        </dt>
        <dd>
            <!a href="@Html.Raw(Model.BlogPostLink)">@Html.DisplayFor(model => model.BlogPostLink)</!a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AspNetCoreVersion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AspNetCoreVersion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/AspNetCoreBlogList/Views/BlogPosts/Details.cshtml
@model AspNetCoreBlogList.Models.BlogPost

@{
    ViewData["Title"] = "View ASP.NET Blog Post Details";
}

<h2>Details</h2>

<div>
    <h4>ASP.NET Blog Post Entry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostImage)
        </dt>
        <dd>
            <img src="@Url.Action("RenderImage", new { Id= Model.BlogPostId })" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BlogPostTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogAuthor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BlogAuthor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TwitterHandle)
        </dt>
        <dd>
            <a asp-protocol="https" asp-host="twitter.com" asp-controller="@Model.TwitterHandle">@Html.DisplayFor(modelItem => Model.TwitterHandle)</a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BlogPostLink)
        </dt>
        <dd>
            <!a href="@Html.Raw(Model.BlogPostLink)">@Html.DisplayFor(model => model.BlogPostLink)</!a>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AspNetCoreVersion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AspNetCoreVersion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BlogPostId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/AspNetCoreBlogList/Views/BlogPosts/Edit.cshtml
@model AspNetCoreBlogList.Models.BlogPost

@{
    ViewData["Title"] = "Edit ASP.NET Blog Post Entry";
}

<h2>Edit</h2>

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>ASP.NET Blog Post Entry</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="BlogPostId" />
        <div class="form-group">
            <label asp-for="BlogPostImage" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostImage" type="file" name="blogImage" class="form-control" />
                <span asp-validation-for="BlogPostImage" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogPostTitle" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostTitle" class="form-control" />
                <span asp-validation-for="BlogPostTitle" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogAuthor" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogAuthor" class="form-control" />
                <span asp-validation-for="BlogAuthor" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TwitterHandle" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TwitterHandle" class="form-control" />
                <span asp-validation-for="TwitterHandle" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BlogPostLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BlogPostLink" class="form-control" />
                <span asp-validation-for="BlogPostLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AspNetCoreVersion" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="AspNetCoreVersion" asp-items="Html.GetEnumSelectList<AspNetCoreVersion>()" class="form-control"></select>
                <span asp-validation-for="AspNetCoreVersion" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/AspNetCoreBlogList/Views/BlogPosts/Index.cshtml
@model IEnumerable<AspNetCoreBlogList.Models.BlogPost>

@{
    ViewData["Title"] = "ASP.NET Core Blog Posts";
}

<h2>ASP.NET Core Blog Posts</h2>

<p>
    <a asp-controller="BlogPosts" asp-action="Create">Create New Blog Post Entry</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BlogPostTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogAuthor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TwitterHandle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogPostLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AspNetCoreVersion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BlogPostTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogAuthor)
            </td>
            <td>
                <a asp-protocol="https" asp-host="twitter.com" asp-controller="@item.TwitterHandle">@Html.DisplayFor(modelItem => item.TwitterHandle)</a>
            </td>
            <td>
                <!a href="@Html.Raw(item.BlogPostLink)">link</!a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetCoreVersion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BlogPostId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BlogPostId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BlogPostId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>